### ISSUE TITLE
Get error when installing

### ISSUE THREAD

**Issue by Johanndut** [haruncpi/laravel-user-activity#1]
I get an error 
In PackageManifest.php line 131:

  Undefined index: name

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by haruncpi** [comment]
It may be composer issue. First try to update composer.
`composer self-update --stable`
Now install the package.
