### ISSUE TITLE
haruncpi -user activity

### ISSUE THREAD

**Issue by Divya-gi** [haruncpi/laravel-user-activity#14]
user activity not showing edit,delete user activities and not insert that details into lgs table

**Comment by haruncpi** [comment]
You must have to use `Loggable` trait into your model. 

Code Example
```
<?php namespace App;

use Illuminate\Database\Eloquent\Model;
use Haruncpi\LaravelUserActivity\Traits\Loggable;

class Student extends Model
{
    use Loggable;

} 
```

**Comment by dwain-lab** [comment]
This was working in V1.0.1, however after upgrading it I am no longer seeing any information on the table for user-activity.  I downgraded to v1.0.1 and it shows the information.

**Comment by keshav1990** [comment]
I have installed this addon but its tracking only user login activity nothing else

**Comment by haruncpi** [comment]
You have to use [Loggable trait](https://github.com/haruncpi/laravel-user-activity/issues/14#issuecomment-755106538)

**Comment by GianmarcoTrustDev** [comment]
i have used use Loggable; in my models but the user activity track only user table

**Comment by jfullstackdev** [comment]
hello there @GianmarcoTrustDev , maybe your situation is like mine ? mine is working now, check this thread 

https://github.com/haruncpi/laravel-user-activity/issues/43
