### ISSUE TITLE
Getting exception while running install command

### ISSUE THREAD

**Issue by sunilsharma0** [haruncpi/laravel-user-activity#15]
php artisan user-activity:install
 

                                                                   
 [InvalidArgumentException]                                       
 There are no commands defined in the "user-activity" namespace.  

I am using Laravel Framework version 5.0.35.
Please help me to resolve it  @haruncpi @affektde @coziboy @fbsoares @MouadZIANI @.

**Comment by haruncpi** [comment]
Laravel 5.0 not support automatic service provider. To fix that, add the service provider manually in app.php file.

```
Haruncpi\LaravelUserActivity\ServiceProvider.php
```

**Comment by sunilsharma0** [comment]
PHP Fatal error:  Cannot use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider because the name is already in use in /var/www/html/eco/api/webservices/vendor/haruncpi/laravel-user-activity/src/EventServiceProvider.php on line 9

Getting new fatal error after manually adding service provider
@haruncpi

**Comment by haruncpi** [comment]
Try it in Laravel >=5.5
