### ISSUE TITLE
Laravel Backpack conflict 404 error

### ISSUE THREAD

**Issue by yacinegithub** [haruncpi/laravel-user-activity#16]
Salam, When usin Laravel Backpack(Laravel admin panel i guess you know it) it ends with a conflict eithet admin/user-activity or admin/dashboard (a route of backpack) both they give 404 erro 

to confirm that i installled Backopack demo (https://github.com/laravel-backpack/demo) app then i added user-activity package then i get the same erro
waiting for any solution bro.

**Comment by haruncpi** [comment]
This package has customizeable route feature. It allow you to change these routes.

Solution:
publish the `user-activity.php` file and change value according to your need.

```
<?php

return [
    'middleware'       => ['web', 'auth'],
    'route_path'       => 'admin/user-activity', //change it
    'admin_panel_path' => 'admin/dashboard', // change it
    'delete_limit'     => 7,

    'model' => [
        'user' => "App\User"
    ],

    'log_events' => [
        'on_edit'    => true,
        'on_delete'  => true,
        'on_login'   => true,
        'on_lockout' => true
    ]
];
```

**Comment by yacinegithub** [comment]
I will try it, thanks
