### ISSUE TITLE
App\User not found

### ISSUE THREAD

**Issue by iamB0rgy** [haruncpi/laravel-user-activity#34]
Hello,

I'm getting this error. 

Class "App\User" not found {"userId":1,"exception":"[object] (Error(code: 0): Class \"App\\User\" not found at C:\\xampp\\htdocs\\pherp\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasRelationships.php:755)

I have checked the config\auth.php and it is correct. 

`    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],`

**Comment by yormy** [comment]
Check the LOCATION of your actual users model :
you specified ```App\Models\User``` and in the config it is without the 'models'
change the config to ```App\Models\User```

**Comment by haruncpi** [comment]
Write it to `config/user-activity.php`
```php
 'model' => [
        'user' => "App\Models\User"
 ],
```
