### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by affektde** [haruncpi/laravel-user-activity#4]
https://github.com/haruncpi/laravel-user-activity/blob/583a2541cbcb6cffa252c874735614c3fb688842/src/Controllers/ActivityController.php#L100

``$all = array_map('reset', DB::select('SHOW TABLES'));``

This is not suppored by posgres databases.

I will try to fork and make a PR. Maybe my first ever :-D Hope I will do it right :-)

**Comment by affektde** [comment]
https://github.com/haruncpi/laravel-user-activity/pull/5
I hope I did everything right with the PR.

**Comment by affektde** [comment]
https://github.com/haruncpi/laravel-user-activity/pull/5/commits/a84cf20a3576c8f5d5c41954bd2702d3889ed7f2

I've also included the new **new Laravel 8 Eloquent Model Conventions**.

So I've changed `App\User` to `App\Models\User`.

**Comment by haruncpi** [comment]
`App\Models\User` namespace is not work below latest version laravel 8.*

If i'm not wrong, most of developer still using below 8.0

**Comment by affektde** [comment]
https://github.com/haruncpi/laravel-user-activity/pull/5/commits/af0df2e30df128cd4881650ea57754b83a6c22de

>App\Models\User namespace is not work below latest version laravel 8.*
>If i'm not wrong, most of developer still using below 8.0

Okay, so with this code both namespaces should work.

**Comment by haruncpi** [comment]
added. thank you!
